module Parser where

import Grammar
import Rules

applyRules :: Node -> [Node]
applyRules eof@(Node EOF _ _) = [eof]
applyRules (Node grammar rules successors) =
  let
    --allSuccessors = applyAllRules successors
    --completeSelf = Node grammar rules allSuccessors
    completeSelf = Node grammar rules successors
    applyRulesFixedPoint self@(Node grammar rules successors) =
      let
        newNodes = concatMap (\f -> f self) $ rules
      in
        -- Now apply the Rules of all the new Nodes generated, and apply the
        -- Rules of all new Nodes generated by this new application, until we
        -- stop creating new Nodes.
        (concatMap applyRulesFixedPoint newNodes) ++ newNodes
  in
    completeSelf : applyRulesFixedPoint completeSelf

applyAllRules :: [Node] -> [Node]
applyAllRules = concatMap applyRules

extractSentences :: [Node] -> [Node]
extractSentences = concatMap extractSentencesFromNode

extractSentencesFromNode :: Node -> [Node]
extractSentencesFromNode eof@(Node EOF _ _) = [eof]
extractSentencesFromNode (Node sentence@(FullSentence _) rules rest) =
    [Node sentence rules (extractSentences rest)]
extractSentencesFromNode _ = []
